notifications:
  email: false
  irc:
    channels:
      - "irc.mysociety.org#fixmystreet"
    use_notice: true
    skip_join: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/863c1892a6a51e5a3b3c

language: perl
perl:
  - "5.14"

env:
  global:
    - "S3_BUCKET=fixmystreet-bundle-cache"
    - secure: "llgWNfR/8pH0HjYpg+xhVxuqTaLC0GGUugfuINiUap7JxzjCZ2rlryxCXA4BCM8GUHa9wlYKhrKCSx+DM3EHRE0cLei7LNxAK1JSXLj3NihFQhqnq64tjDwGCSA4l7mlqErA7DK4Dpmh+hBp5f680akITAInM92CbwQZxLDYaCU="
    - secure: "qW+WCgAF68itADxcbcq+nCnKx3vf3GX73HMfjfbkFFUsYmIR+ZaJ9yQMnGJwxIpCHTWLAeqyx4KO8N8T3GmNdKYzIMZemOzp4ED29YC31QOQeq1CwNp2hD5sq/o47d2BzXWwMYNvNXfxz1K6r2c6EMPUtu8X3B8ExZq1RzSFdXs="

before_install:
  - sudo locale-gen cy_GB.UTF-8 en_GB.UTF-8 nb_NO.UTF-8 de_CH.UTF-8 sv_SE.UTF-8
install:
  - .travis/install
before_script:
  - ./bin/make_po FixMyStreet-EmptyHomes
  - ./bin/emptyhomes/make_welsh_po
  - commonlib/bin/gettext-makemo FixMyStreet
script: "bin/run-tests t"
after_script:
  - .travis/after_script
